### ISSUE TITLE
Margins are no longer settable

### ISSUE THREAD

**Issue by ryanackley** [readium/readium-js-viewer#179]
Recent changes related to margins seems to remove the ability to change the margin size. Not sure if this is by-design. @danielweck is on holiday and he made those changes.

We need to determine if we will do auto-margins moving forward. If so, we need to remove the setting from the dialog. If not, we need to make them settable again.

**Comment by danielweck** [comment]
Here, we need to do two things:

1) make the Chrome extension behave like it used to: the "margins" slider in the settings dialog should visibly affect the left/right blank areas on either sides of the single or double page layout, in addition to setting the constant margin / blank border that surrounds each page (which in turn determines the width of the dividing area between two consecutive pages within a synthetic spread).

2) make it possible to configure the width thresholds of text "columns":
- min value so that a two-page spread of reflowable documents automatically switches to single-column mode, when the lines of text become unreasonably narrow,
- max value so that text does not run across excessive horizontal distances.
Right now these values are hard-coded, see:
https://github.com/readium/readium-shared-js/blob/develop/js/views/reflowable_view.js#L510

Some users *prefer* wide columns (even as far as full stretch on landscape displays), whilst others *need* to be able to constrain the horizontal runs of text to a reasonable distance (for accessibility reasons). Because of the broad variety of preferences, it would be nice to expose the min-max customisation in the settings dialog of the Chrome extension. This could replace or supplement the existing "margins" slider referred-to in (1).

**Comment by danielweck** [comment]
Addressed via https://github.com/readium/readium-js-viewer/pull/498
(fine-tuning of slider values in develop branch)
