### ISSUE TITLE
Change toolbar so it appears only when the mouse is over it or it gets the focus

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#182]
Currently the toolbar disappears after a short interval but immediately re-appears if the mouse is moved.  this is mildly annoying to some people (and "super annoying" to others...).  

See: http://idpf.org/forum/topic-1755

iBooks only makes the toolbar appear if the mouse pointer is actually over the toolbar area OR if the keyboard shortcut is used to give a toolbar control the focus.
The Chrome App should behave the same way.

**Comment by danielweck** [comment]
Duplicate, with screenshots: https://github.com/readium/readium-js-viewer/issues/389

**Comment by becka11y** [comment]
We also need to make certain that tabbing into the toolbar forces it to become visible.  For example, if focus is on the close icon of the table of contents and the user presses shift-tab, I believe the toolbar should appear (if it is not already visible) with focus on the enter full screen icon.  This could be confusing to sighted keyboard users who might be surprised at focus going to something they couldn't initially see on the screen but I think that consistent behavior for non-sighted users is also important. They will learn that the toolbar is always in the focus ring.  I'm open to other interpretations, though. I can't find good documentation for using iBook with the keyboard when VoiceOver is NOT running.  I don't believe you can fully navigate iBooks with only the keyboard unless VO is on.  Thus, I couldn't test how iBooks handles this situation.

**Comment by ryanackley** [comment]
Pushed a fix to develop. Want to get some people trying it out before I declare this fixed.

@becka11y Tabbing from the ToC isn't an issue since the navbar never disappears when the ToC is open. This is the current behavior so it's nothing new. I'm wondering if we should focus and display the navbar when someone hits tab while the navbar is hidden. Thoughts?

**Comment by becka11y** [comment]
We probably shouldn't focus the tab bar when a user presses the tab key because they could want to tab to the next taxable item within the content.  Although, as I am playing with this, I often don't see the nav bar disappear at all? It seems to stay visible even when the toc is not displayed?  I'm playing with it more now in Safari.

**Comment by danielweck** [comment]
The updated navbar show/hide behaviour looks fine to me. Mouse usage is intuitive, and keyboard navigation works as usual: e.g. `x` and `v` single-key accelerators to hide / show the navbar (respectively), and tab-cycling into the navbar automatically reveals it. As usual, when the keyboard focus is within the navbar, the navbar remains visible.
I agree with @becka11y that once I start using keyboard navigation, the navbar show/hide behaviour somehow feels less "predictable. Sometimes I am not able to switch back to auto-hide mode (even after clicking within the displayed document text).

**Comment by ryanackley** [comment]
@danielweck @becka11y Thanks for testing. This is what I was worried about. I must have missed an edge case that stops the show hide loop.
