### ISSUE TITLE
HTTP Byte Range detection too severe

### ISSUE THREAD

**Issue by lambdafu** [readium/readium-js-viewer#243]
Many HTTP Servers may support HTTP Byte Range but not advertise it via Accept-Range header.  In fact, RFC 2616 says:

      Origin servers that accept byte-range requests MAY send
          Accept-Ranges: bytes
      but are not required to do so. Clients MAY generate byte-range
      requests without having received this header for the resource
      involved.

Readium checks the presence of the header to detect the feature.  This will fail on perfectly functional servers.

Is it feasible to change the detection to try a byte range request and see if it works?  Or is there risk that a non-supporting web server sends the full file instead?  I don't know!

**Comment by danielweck** [comment]
@mahag asked:
https://github.com/readium/readium-js-viewer/issues/266
"
I did try the steps on web server for basic ebup reader.
I placed content inside reader-js-viewer folder on server and try to open url
yourdomain/readium-js-viewer/simpleviewer.html?epub=epub_content/moby_dick

But it is nt showing anything since i didnt configure web server for http byte serving.
I have windows server 2012 with IIS version 8 . How can I acheive that ?
"

**Comment by danielweck** [comment]
Fixed via NPM build workflow refactoring:

https://github.com/readium/readium-js/blob/develop/package.cson#L105
```cson
#    "zipjs": 'gildas-lormeau/zip.js'
#    "zipjs": 'ryanackley/zip.js'
    "zipjs": "danielweck/zip.js"
```
=>
https://github.com/danielweck/zip.js/commit/8f4340254f5aa7365955c1ca73f07aabab2707d7
