### ISSUE TITLE
How to configure server for http byte serving on web server?

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#266]
I did  try the steps on web server for basic ebup reader.
I placed content inside reader-js-viewer folder on server and try to open url
yourdomain/readium-js-viewer/simpleviewer.html?epub=epub_content/moby_dick

But it is nt showing anything since i didnt configure web server for http byte serving.
I have windows server 2012 with IIS version 8 . How can I acheive that ?

**Comment by danielweck** [comment]
Answered here:
https://github.com/readium/readium-js-viewer/issues/197#issuecomment-56590532

(closing as duplicate)

**Comment by danielweck** [comment]
PS: to obtain information about how to configure HTTP v1.1 Byte Range support in Microsoft IIS, I suggest asking on the relevant forum / mailing list.

**Comment by mahag** [comment]
I did ask abt configuring byte range on IIs forums. I got that 
"IIS8 natively supports "byte serving" (this is advertised via the HTTP accept-ranges:bytes header). Generally there is nothing you need to configure."

So why readium isnt working. I just placed readium-js-viewer content inside a folder on my server and tryin to access it through www.domain.com/readium-js-viewer/simpleviewer.html?epub=epub_content/moby_dick. But still not working. I cant figure out what is missing

**Comment by danielweck** [comment]
Thank you @mahag for clarifying the IIS situation.

Could you please make sure to use the code in the develop branch?
Then, could you please build the Readium "cloud reader" using Grunt?
```
grunt cloudReader
```
=> which produces `build/cloud-reader/` (just make sure to copy/paste your desired `epub_content/` folder contents)

Alternatively:
```
grunt cloudReaderLite
```
=> which produces `build/cloud-reader-lite/` (equivalent to simpleviewer.html, but in aggregated/minified form)

Or, if you are not able to build Readium using Grunt, try the index.html file at the root of the repository instead of simpleviewer.html

/Daniel

**Comment by danielweck** [comment]
PS: the forward slash in the URL query parameter is usually percent-escaped by the web browser automatically, but just double-check that you are indeed using the correct syntax:

`http://192.168.1.68:8080/index.html?epub=epub_content%2F___`
(where the "___" characters are the folder name for a given unzipped EPUB inside the `epub_content` directory)

**Comment by mahag** [comment]
Ok I will download the develop branch and send it to my server in folder reader-js-readium-develop.
But can you guide how to build it using grunt. 
I did try before to call grunt from command prompt after going to the readium folder where i have the content and i run grunt over it. I get 'grunt' is not recognized as an internal or external comman,operable program or batch file. Is what am doing correct?

**Comment by danielweck** [comment]
Okay, ignore the Grunt command for now (it is a developer-oriented feature), just test index.html on your server and please report back (you should at least have access to the ebook library view, from where you should be able to click on an EPUB cover).
It should look like that:
http://readium-cloudreader.divshot.io
(with your own selection of ebooks in the `epub_content` folder)

**Comment by mahag** [comment]
I did try
www.mydomain.com/readium-js-viewer-develop/simpleviewer.html?epub=epub_content/moby_dick
and 
www.mydomain.com/readium-js-viewer-develop/index.html
on google chrome,still nothing showed just the dark header without readium logo or settings on it.

**Comment by danielweck** [comment]
The dark horizontal navigation bar at the top indicates that the CSS is loaded correctly. The absence of the Readium logo indicates that some files / folders are missing. Are you able to share a private URL so I can take a look at the debug console messages on my end? Otherwise, just open the console with your browser and try to see what is missing.

**Comment by mahag** [comment]
If i try to open images or logos through url from my domain , it is working.
Can i send you the url privately ? through mail?

**Comment by danielweck** [comment]
Sure: daniel.weck@gmail.com

**Comment by danielweck** [comment]
Thank you for sharing the private URL.
It looks like folders/files are missing, make sure you upload everything to your server.

Better even, follow the instructions to build Readium, as this will minimise and optimise the reader application (you are only supposed to use the basic index.html and simpleviewer.html for testing your ebooks, it is better to deploy a proper build version of Readium):

(extract from https://github.com/readium/readium-js-viewer/ home page "documentation")

```
install Node.JS (details depend on your operating system => http://nodejs.org/)

install the Grunt build tool: npm install -g grunt-cli

install the project's dependencies: npm install
```

**Comment by mahag** [comment]
For extracting i am using the download as zip button and then i extract to a folder "readium-js-viewer".
For npm install -g grunt -cli and npm install do i run them over readium-js-viewer folder  from command prompt? I mean go to folder readium-js-reader using cd command and then call the installs?

**Comment by danielweck** [comment]
The source code ZIP download on the "release" page is incomplete, I will report a separate bug (thank you for reminding me!):
https://github.com/readium/readium-js-viewer/releases
https://github.com/readium/readium-js-viewer/archive/0.16.0.zip

The source code ZIP download on the "tree" page will not work, because GitHub does not include submodules (and because index.html and simpleviewer.html require a missing build/version.json file):
https://github.com/readium/readium-js-viewer/tree/develop

The "proper" way to deploy Readium cloud reader is by building it with Grunt (`grunt cloudReader` or `grunt cloudReaderLite`), or *at least* to run the Grunt command without parameters (`grunt`) so that the `build/version.json` files gets created once (and accessorily a local Node-Express web server is launcher on port 8080).

So to answer your question: yes, you need to use the command line. However, I am going to ask our developer team about the "release" zip: it would be good if this package could include a ready-to-deploy build of Readium, including *all* the necessary files, so that the contents can just be uploaded as-is onto an HTTP server.

Daniel

**Comment by mahag** [comment]
Can you guide me plz how to acheive this ?
The "proper" way to deploy Readium cloud reader is by building it with Grunt (grunt cloudReader or grunt cloudReaderLite), or at least to run the Grunt command without parameters (grunt) so that the build/version.json files gets created once (and accessorily a local Node-Express web server is launcher on port 8080).

**Comment by mahag** [comment]
When calling grunt through command prompt am getting
'grunt' is not recognized as an internal or external command,operable program or batch file

**Comment by danielweck** [comment]
Note: I filed a new issue so that we implement an easier way for non-technical users to download a working (ready-to-deploy) build of Readium available from the latest source code on the `develop` branch:

https://github.com/readium/readium-js-viewer/issues/268

**Comment by danielweck** [comment]
You must install Node from http://nodejs.org
Then call `npm install -g grunt-cli`, then invoke `npm install`.

Let me send you a pre-built zip, so you can test your books.
