### ISSUE TITLE
Paragraph numbering for headings not aligned properly

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#267]
From Rod Shaw <R.J.Shaw@lboro.ac.uk>
Publications and Media Manager / Conference Editor
Water, Engineering and Development Centre (WEDC)
School of Civil and Building Engineering
The John Pickford Building
Loughborough University 
Leicestershire  LE11 3TU  UK

I have created an epub3 file from Adobe InDesign CC and it renders fine in iBook on the Mac, and mostly does in Readium.

However, as I have used paragraph numbering for headings, the number itself isn’t aligned with the text when viewed in Windows / Chrome / Readium. The same goes for Table heading, boxes figures etc.

**Comment by danielweck** [comment]
Reflowable or fixed layout?
Do the raw HTML files display correctly in vanilla web browsers?
EPUB download link?
:)

**Comment by Rod-at-WEDC** [comment]
I notice this morning that the file reads well using Readium v 2.15.2 on OS Mavericks. However, on Windows 7 using Chrome and launching the app (also v 2.15.2) from the same location, the issue remains. The file location is at:

http://wedc.lboro.ac.uk/resources/e/dl/unit.epub

The file was created using InDesign CC and exported using the fixed layout option.

Any help would be most appreciated! 

Rod

(P.S. Not sure what a vanilla web browser is....)

**Comment by Rod-at-WEDC** [comment]
... It doesn't open in Firefox and Adobe Digital Editions scrambles it too...

**Comment by danielweck** [comment]
Thank you for sharing the EPUB download link.

By "vanilla" web browser I meant "regular" web browser, i.e. without Readium (just open the HTML file directly, to see how it looks on its own).

I can see a slight vertical offset in Readium-Chrome-Windows (numbers are too high), compared with Readium-Chrome-OSX. I am afraid that this appears to be a Chrome-specific web browser "bug" (CSS rendering inconsistency), Readium cannot do anything about it.

Also note that in Internet Explorer (Readium "cloud reader", not Chrome extension) the heading text is overlapping, so there seems to be other CSS rendering misbehaviours in this ebook. In fact, this problem is reproducible in Chrome-OSX when opening the XHTML file directly (i.e. when no CSS scaling / transform is applied to the document).

This indicates that the CSS generated by InDesign is somewhat incorrect. The exported fixed-layout EPUBs are probably only tested with iBooks ... which would explain the cross-platform inconsistencies. I suggest you report this to the InDesign team.

Let us know if you notice other problems, we like to hear about "real world" problems related to fixed-layout / reflowable EPUBs exported from authoring tools.

Regards, Daniel

**Comment by Rod-at-WEDC** [comment]
Thanks!
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Rod Shaw
Publications and Media Manager / Conference Editor
Water, Engineering and Development Centre (WEDC)
School of Civil and Building Engineering
The John Pickford Building
Loughborough University
Leicestershire  LE11 3TU  UK

T: +44 (0) 1509 222886
F: +44 (0) 1509 211079
W: http://wedc.lboro.ac.uk/

Developing knowledge and capacity
in water and sanitation

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Call for Papers!
The 38th WEDC International Conference
27–31 July 2015 – To find out more visit:
http://www.wedcconference.co.uk
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Download free resources from the WEDC Knowledge Base:
https://wedc-knowledge.lboro.ac.uk/

Follow us on Twitter and Facebook
https://twitter.com/wedcuk<http://twitter.com/wedcuk>
https://www.facebook.com/wedc.lboro

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[cid:1131E297-D391-4526-97F6-AE6A6354A0C9]

**Comment by Rod-at-WEDC** [comment]
Thanks, Daniel, this is helpful.
