### ISSUE TITLE
EPUB fails to load after many ProgressEvent error messages

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#280]
Trying to load the video references in readium-js-viewer #265  takes a long time then apparently finishes, but no EPUB is then in the library.  
The console shows:

    Discontiguous selection is not supported.
    readium-all.js:16342 'KeyboardEvent.keyLocation' is deprecated. Please use 'KeyboardEvent.location'     instead.
    chrome-extension://hfhdfihjnecbeaocmenccjjikddhaijm/fonts/glyphicons-halflings-regular.woff2 Failed to load resource: net::ERR_FILE_NOT_FOUND
    filesystem:chrome-extension://hfhdfihjnecbeaocmenccjjikddhaijm/persistent/epub_library.json Failed to             load resource: net::ERR_FILE_NOT_FOUND
    readium-all.js:14398 Arguments[1]     scripts/readium-worker.js:506 Uncaught #<ProgressEvent>
  

and dozens more Progress Event errors exactly the same.

**Comment by rkwright** [comment]
I have created a slimmed down version of the file with only two videos.  The EPUB plays correctly in iBooks and the OSX Launcher.  However, in the Chrome Extension it has several problems:

* the progress event errors listed above
* the cover image is sometimes rendered in the catalog, sometimes not
* the poster image (just the EPUB logo) is not scaled correctly and sometimes not at all
* the videos do not play

the video is here
https://readiumfoundation.box.com/shared/static/jsitratcgydmarb4qoypvrc4k0drh381.epub

**Comment by danielweck** [comment]
I cannot comment on the issues that look specific to the Chrome extension, but the video problems are detailed in the original issue:
https://github.com/readium/readium-js-viewer/issues/265#issuecomment-73018762
See my recent comment / update.
@rkwright , I used your sample EPUB (thank you), but I tweaked it to display more reflow pages / CSS columns (otherwise the test is incomplete).

**Comment by danielweck** [comment]
PS: @rkwright I also removed the poster image and width/height dimensions in your sample EPUB, as this skewed the outcome in my video tests: mismatched aspect ratio is handled differently by Chrome, Firefox, Internet Explorer (I am testing heavily on Windows at the moment, not as much on OSX). For further details, see issue 265 linked above.

**Comment by ryanackley** [comment]
This seems to be caused by the chrome extension reaching the maximum amount of in-memory binary storage allowed by Chrome. The limit is around 500MB. 

Readium unzips the entire epub in memory, then attempts to write each uncompressed entry to the file system. If you had 1:1 compression (no compression) ratio this would mean you double the file size in memory at some point. However, it's most likely much more since the compression ratio is usually lower than 1. 

I will try to optimize the unzip pipeline to improve the current situation but this will just increase the limit, not remove it. In the meantime, to work around this issue, you can unzip the epub yourself then import it into the chrome extension using the "Unpacked Directory" option.

**Comment by ryanackley** [comment]
The sample file I was sent now works. Also, I've made changes to significantly increase the limit. The limit is based on the size of individual files contained in the zip not the zip itself. Theoretically, you should be able to extract any individual file less than 500MB. So you could have a 150GB epub file and as long as no individual file in the epub was >500MB, it should work. (It might take until xmas to extract though).
