### ISSUE TITLE
Icons out of place and red text

### ISSUE THREAD

**Issue by SpellCat** [readium/readium-js-viewer#300]
Hey guys, i just cloned the master branch to my server and the result looks like this:

![Image of readium]
(https://dl.dropboxusercontent.com/u/63524573/Captura%20de%20Tela%202015-03-17%20%C3%A0s%2021.35.43.png)

Currently on Safari, it looks the same on Chrome.

Can you guys give me a hand? Thanks in advance =)

**Comment by rkwright** [comment]
Some clarifications, please. You are building/deploying the CloudReader, correct?  Can you try this with the develop branch - or release/0.17.  We are just about to push a new update to master (and merge back to develop) from release/0.17.  I have heard a report about this see issue #291 

I believe this issue is a duplicate.  Will close for now.
