### ISSUE TITLE
ReadiumSDK.reader.bookmarkCurrentPage()

### ISSUE THREAD

**Issue by expouic** [readium/readium-js-viewer#333]
Can anyone explain why the method ReadiumSDK.reader.bookmarkCurrentPage()  response with contentCFI and when need using this value, for example on method updateSettings, need to change contentCFI to elementCFI ?

Would it not be simpler change the name of contentCFI to elementCFI on ReadiumSDK.reader.bookmarkCurrentPage()?

**Comment by JCCR** [comment]
You are correct about the lack of consistency between API calls, and there are more than just this. We are working on improving this.

The reason as to why they are named differently is because a "contentCFI" is a more general type as it could be a range CFI with offsets or an element CFI. The updateSettings works best if given an elementCFI, if you provide a range CFI (which bookmarkCurrentPage might generate) then it won't take into account the offset information.

**Comment by danielweck** [comment]
Closing, see:
https://github.com/readium/readium-shared-js/issues/157#issuecomment-100615114
