### ISSUE TITLE
Messages passed to iframe parent are not received by parent

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#356]
In order to implement the ESC pub-sub protocol, we need to be able to pass messages from a document within an iframe in the EPUB up to it's parent.  The supplied samples do this.  It works fine in SDKLauncher-OSX and iBooks and the XHTML/JS works fine in the browser.  However, in the Chrome Extension, the message never reaches the parent.  There is no error warning in the console.
The code demonstrating this is located on githubin

readium-test-files/issues/readium-js-viewer/356

For testing in the browser, just extract the XHTML and JS files from the EPUB.

**Comment by danielweck** [comment]
@rkwright 

- Your EPUB works fine in the cloud reader (same console output as the
raw HTML: "onLoad event in child! + onLoad event in parent + Got event
in parentHello Dad").

- However, your EPUB fails in the Chrome extension / packaged app.
This is a bug. The window.top/parent properties are correctly
redirected ; see Ryan's first link
https://github.com/readium/readium-js-viewer/blob/master/chrome-app/epubReadingSystem.js#L2
; in *spine item* HTML documents (so that they become unable to access
the reading system scope) but the window.top/parent properties in
*inner iframes* (e.g. widgets) should be untouched. See for example
the iOS-WKWebView implementation:
https://github.com/readium/readium-sdk/commit/41d0770bceaa2e63c6ce511f8a76289d9f551e85
Note that iOS-UiWebView and OSX-WebView do not require the
window.top/parent trick, as the EPUB content is served from a
different domain/origin than the application code.

- Now, this discussion actually highlights a bug in the cloud reader
(see Ryan's second link:
https://github.com/readium/readium-js/blob/develop/epub-modules/Readium.js#L39
). I have logged a separate issue: https://github.com/readium/readium-js/issues/107

**Comment by danielweck** [comment]
Related issue (follow-up): https://github.com/readium/readium-js/issues/107

**Comment by rkwright** [comment]
From @ryanackley 
With regard to the window.top/parent redirect code, the protection it
provides is really flimsy and possibly misleading. It really couldn't hurt
before but now that we're talking about working around various edge cases to
keep it in, we should just get rid of it.

There are a couple of problems with it. First, there are other ways to break
out of the sandbox. For example,
window.frameElement.ownerDocument.defaultView works. In Chrome, all of the
objects in that chain are readonly. Second, it isn't W3C compliant. Both the
parent and top property are supposed to be readonly. This means this could
just stop working and it probably doesn't work across all browsers. For
example, in casual testing with IE11, setting window.top or window.parent
seems to have no effect on the values. They still return the correct window.
I haven't tested this in FF, but in the Mozilla window.top documentation it
mentions that this has been read-only since FF 6.0.

**Comment by rkwright** [comment]
from @danielweck 
Thanks for bringing to my attention the
window.frameElement.ownerDocument.defaultView accessor. I updated the
documentation, and I will update the EPUB test too:

https://docs.google.com/document/d/1GK1aVsrTv23WroBWMX-XiwYtXbq6huW_pK8QXRaY6XQ

And yes, window.top is read-only in all browsers, window.parent is
also read-only in IE.
None of the window.frameElement.ownerDocument.defaultView accessors
can be overwritten.

In other words, window.top is a reliable, trivial vector of attack in
all ReadiumJS-based implementations. ReadiumSDK-based apps benefit
from partial resource sandboxing thanks to HTTP domain isolation ...
assuming that only EPUB content is served via HTTP, and that the
Readium shared JS rendering engine is served from the file://
app-bundle origin (which, as explained before, is not the case anymore
with iOS / OSX WKWebView, so that is not a long term solution either).

**Comment by danielweck** [comment]
Addressed in cloud reader and chrome extension (feature branch, not merged to develop yet):
https://github.com/readium/readium-js/commit/6e075512968e0852f45f94b2f9524a625c2d8fab
https://github.com/readium/readium-js-viewer/commit/6ef26a210129c85578c5903c8904039451c51f8e

**Comment by rkwright** [comment]
Re-opening since the fix is not in the develop branch and this is blocking widget work.  Note also that it does not work properly in the SDLauncher-OSX in the develop branch either.  I have a bare-bones sample file, TinyLogger.epub, that works fine in iBooks, but only partially in the Chrome Extension and not at all in OSX.  I will post the test file shortly.

**Comment by danielweck** [comment]
Merged:
https://groups.google.com/forum/#!topic/readium-dev/sc2cRP-lTHs

**Comment by danielweck** [comment]
I added a comment for iOS WKWebView:
https://github.com/readium/readium-sdk/commit/41d0770bceaa2e63c6ce511f8a76289d9f551e85#commitcomment-12118024
