### ISSUE TITLE
Ctrl + shift + i over index.html page is showing the content of the epub

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#365]
After opening the .epub file with index.html under cloud-reader and clickin Ctrl + Shift + i the developer tool opens on google chrome. Once we click on search image and select some text in the epub displayed we can see the whole html content of that file opened under elements tab of the developer tool. This means that epub content can be violated and hacked by copy/paste from elements tab.
Is there a way to prevent this?

**Comment by ryanackley** [comment]
There is no way to prevent this. 

I'm asuming by "hacked" you mean they can copy the epub without permission? Note that readium-js-viewer opens only DRM-free epubs at this time.Therefore, this concern seems missplaced since the user can simply unzip the epub file (an epub file is just a .zip file with a .epub extension) and look at and copy the contents without even opening it in Readium. 

Also since there is no DRM, the user doesn't even need to do this. They can just email it to whomever they want or put it on a website for other people to download. Anyone who has a copy can then open it in Readium.
