### ISSUE TITLE
Latest Chrome breaks Media Overlays (Linux-specific)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-js-viewer#376]
Reported by Alberto Pettarin:

updated Chrome (43.0.2357.134), Readium 2.18.1, Debian. MO no longer work. 1st fragm highlighted, no audio, no autoplay

**Comment by pettarin** [comment]
The <audio> element, in the same configuration and with the same MP3 file that should have been loaded by MO, works.

As briefly said on Twitter, when I go to a XHTML page with MO, and click on the Play/Pause button, the first MO fragment gets highlighted, but no audio is played. Moreover, the active fragment does not get updated --- that is, the highlight stays on the first fragment.

When I click on another MO fragment, the highlight is applied to it, but again no audio or auto-play.

The problem exists for both an EPUB loaded from unpacked directory or from zipped container.

**Comment by rkwright** [comment]
This is still open, but seems to be specific to Linux so unfortunately not a high priority.

**Comment by danielweck** [comment]
EPUB3 Media Overlays playback on Chrome for Windows works fine, it seems.
http://development.readium.divshot.io/?epub=epub_content%2Fepub30-test-0120-20150521.
(also tested with fixed-layout / pre-paginated talking books)
I am afraid this looks like a Linux-specific bug.

**Comment by pettarin** [comment]
Very sad.

**Comment by danielweck** [comment]
@pettarin just in case you have some time to investigate this further, could you please set `DEBUG` to `true` so that HTML5 audio -related events get printed into Chrome's console:

https://github.com/readium/readium-shared-js/blob/develop/js/views/audio_player.js#L38

I remember having to implement various audio preload+buffer-sync strategies depending on target platforms (Android-Chromium and iOS, for example). HTML5 audio ; in my experience ; has been pretty inconsistent when dealing with fine-grained synchronisation. On top of that, I was able to observe codec-specific issues (typically with Media Overlays: MP3 vs. MP4).

**Comment by pettarin** [comment]
Alright, I'll what I can do to diagnose the problem.

**Comment by rkwright** [comment]
@pettarin   Thanks!  We would love to fix this, but we have limited resources and Linux is not a mandate from the Readium board.  That said, please provide us as much info as you can and we will help as much as we can.

**Comment by pettarin** [comment]
I updated to the latest Chrome packaged for Debian (44.0.2403.157), but the problem is still there.

I set `DEBUG` to `true`. After starting the MO by clicking on the Play button on the GUI, I can see the various 0-10, X, Y, Z events fired. Still, no audio.

With `DEBUG=true` and the inspector console open, I can get audio and MO highlighting auto-playing, but not deterministically, just at times and with no evident relation to the state (if I left the EPUB open at the same XHTML asset or not, or with MO playing or paused, etc.).

With `DEBUG=false` I get the following two errors.

The first when opening the EPUB in the library:

![2015-08-21-17 01 58](https://cloud.githubusercontent.com/assets/4086163/9411951/62694528-4829-11e5-9f81-386b921e66a0.png)

The second when pressing the MO play button:

![2015-08-21-17 02 37](https://cloud.githubusercontent.com/assets/4086163/9411968/7e1776dc-4829-11e5-8235-729628f6c8a2.png)

I am not sure if the "unload is not available in packaged apps." message is actually relevant.

Instead my impression is that, for some reasons, the audio data cannot be retrieved via JS from the temporary/Chrome-private location where the MP3 file is located. However, the same MP3 is played normally when launched from the `<audio>` element. (I am trying with one of our short stories:  http://www.readbeyond.it/samples/bierce01.epub )

**Comment by danielweck** [comment]
Re. `unload is not available in packaged apps`, known (benign) "issue" with Chrome, see:
https://github.com/readium/readium-js-viewer/issues/341

**Comment by pettarin** [comment]
I have found the problem, and it is an ugly one.

MO works correctly --- reflowable/pre-paginated, unpacked/EPUB --- as long as there is no `<audio>` element in the XHTML file which has `src` pointing to the same MP3 of SMIL.

To reproduce: e.g. modify `basic_tests.xhtml` inserting: `<audio src="../audio/basic_tests.mp3" controls="controls" />` under the heading.

I guess that the JS fiddles with the `<audio>` element(s), and it gets "confused".

You might want to test this on other OSes as well, as it does not seem related to Linux alone.

Of course I shall not explain why this issue is very critical to me, the publishers I worked for, and ultimately my users --- in all the commercial EPUBs I did, I had to include the `<audio>` as a "fallback" for people using e.g. iBooks (which is not able to play MOs) so that they could still listen to the audio while reading the text.

**Comment by pettarin** [comment]
Another way to reproduce the issue: using the test suite 0120 EPUB, first stop MO. Then go to the "Embedded Media" page, and then start MO again (either play button or by clicking a phrase). Highlight but no audio.

(If instead MO lands on "Embedded Media" by continuing from the previous XHTML, MO seems to work.)

**Comment by danielweck** [comment]
Thank you for your detailed report @pettarin 
Unfortunately I am not able to reproduce the bugs you are describing (I tried adding an `audio` element as you suggested, and I also tested the "Embedded Media" page).
I am in Windows 10, I tried the latest versions of Chrome, Firefox, Internet Explorer, and Edge.
I am using the build of the cloud reader from the "develop" branch (locally on my machine), which is also automatically deployed here:
http://development.readium.divshot.io/?epub=epub_content%2Fepub30-test-0120-20150521.

**Comment by pettarin** [comment]
Thank you for taking time to check it out.

It seems a Linux-specific problem. I asked around, and I got:

6 Windows 7/8/10 users: all ok
2 OS X users: ok
1 Ubuntu: issue triggered
3 different Debian machines (of mine): issue triggered

It might have something to do with the Google google-chrome builds. (Not tested in chromium.)

Anyway :(

**Comment by pettarin** [comment]
BTW, the issue is still present, with the same symptoms and diagnosis, in the latest Debian Chrome (2017-01-18):

```
$ google-chrome --version
Google Chrome 55.0.2883.87
```

**Comment by danielweck** [comment]
Thanks Alberto!

**Comment by pettarin** [comment]
I recently updated iceweasel on Debian (aka Mozilla Firefox 45.9.0), now the issue seems gone.

You can close it, if you like.

**Comment by danielweck** [comment]
Many thanks!
