### ISSUE TITLE
npm run http:watch starts two local http servers

### ISSUE THREAD

**Issue by ryanackley** [readium/readium-js-viewer#397]
It's not clear why this is necessary. Isn't it possible to reference a subfolder of the first http server since it runs at the root of the directory?

**Comment by danielweck** [comment]
These two separate HTTP server instances run on different domains (IP + port), which effectively implements distinct origins for the app vs. ebooks library (HTTP CORS support), despite the fact that they are running "locally".
A single server root can also be used, with the distributable (fully-built) packages, see documentation here: https://github.com/readium/readium-js-viewer/blob/develop/README.md#distribution
At development time though (i.e. any app bootstrapper from the `dev` folder), the two separate HTTP servers are currently required. Are you facing problems because of this?

**Comment by ryanackley** [comment]
I found it very confusing since it launches two browser tabs with different localhost addresses. Your documentation is telling me to navigate to a page. It took me some time to figure out which tab I should use and where to go since neither of those tabs are taking me to the reader. 

Also, maybe it's just me, but it seems messy. I don't want two http servers running locally when it's not needed. CORS is a feature we support but it's not necessary for development. Maybe have a CORS_require.js and a CORS_index.html. I hate to add to this juggernaut of a build system we have now but I really think it's important that there be a version of the simplest possible setup for doing development.

**Comment by danielweck** [comment]
Right, the web browser auto-open of 2x tabs is quite confusing. An alternative, more user-friendly approach would be to open the "no-optimize" RequireJS application bootstrapper in the dev folder.

I agree that it would be nice to have a 1x HTTP server mode, probably as the default option. Then, users / testers who want to ensure that Readium runs fine over HTTP CORS could regularly run checks using the 2x HTTP server mode.
On the other hand, it is worth noting that the current default HTTP CORS setup allowed us to instantly discover the `.cssRule` caveats in @JCCR 's "font loader" implementation.

**Comment by danielweck** [comment]
Fixed: https://github.com/readium/readium-js-viewer/commit/e4d254fa9dce6ae9101a8e8126114c041717e27e
