### ISSUE TITLE
Navigation in 3M Compass eBook is broken in some browsers/platforms

### ISSUE THREAD

**Issue by rkwright** [readium/readium-js-viewer#508]
This is a 3M-generated (by a consultant, holbrook.com) eBook from InDesign.  It is very complicated with lots of video, it's own navigation patterns and so on.  It has so far generated 3 different issues, this one as well as #507 and #350.
 
### This issue is a:

*(choose an option)*

* Bug report
* Feature request
* Enhancement suggestion
* Question
* Other?

### Related issue(s), pull request(s)

See also #NUMBER

### Expected behaviour

Should do...

### Observed behaviour

Instead, does...

### Steps to reproduce

1. Step 1
2. Step 2
3. etc.

### Test file(s)

*(if relevant, please indicate public EPUB URL(s), or whether you can share ebook(s) privately)*

### Product

*(choose appropriately)*

* Readium Chrome extension
  * latest official version available from the Chrome Web Store
  * custom build
* Readium cloud reader app
  * latest development build uploaded at https://readium.firebaseapp.com
  * custom integration (public deployment URL?)
* Native application (ReadiumSDK C++)
  * official "launcher" sample
  * proprietary app
* Hybrid app (ReadiumJS)
  * Electron
  * Apache Cordova
* Other?

### Web browser

*(choose appropriately)*

**Please indicate version if possible** 

* Chrome
* Firefox
* Internet Explorer
* Edge
* Opera
* Other?

### Operating system

*(choose appropriately)*

**Please indicate OS version** 

* Windows
* OSX
* Linux
* iOS
* Android
* Other?

### Additional information

...

**Comment by rkwright** [comment]
Doh!  I think this is pilot error on my part.  There ARE only 4 main "pages" in the book, i.e different "Compass Pages". Then "entering" the chapter takes you to the "launch page" for that chapter.  On each of those "launch pages" are a bunch of "products".  Each product number is a link to a popup page - sort of a linear="no" workflow.

**Comment by danielweck** [comment]
Let's go back to basics. This HTML+JS content *should* work in regular web browsers (let's ignore Readium for now). I'm on Windows 10. Let's open `OEBPS/compass2015_h_v31_ReadiumChange-1.xhtml`. Symptoms:

1) The rendering viewport seems to scroll too far (blank space right and bottom edges of the page)
**Chrome** (small amount of extra scrolling), Edge + IE (really large amount of scrolling)
Firefox works okay.

2) In-page interactions (icon clicks, popup dialogs, etc.) fail to trigger
**Chrome** (!)
Firefox, Edge, IE work okay. I am able to experience the full HTML+JS navigation.

So, no wonder why nothing works in the Readium Chrome extension :)  (at least, in my tests, on my computer)

**Comment by danielweck** [comment]
Now, having tested vanilla web browser, let's see what happens **in Readium** (cloud reader, so we can tests several web browsers, not just Chrome):

**Firefox**: everything works fine.
**Chrome**: in-page UX does not respond (same as vanilla web browser experience)
**IE** + **Edge**: in-page links / navigation results in 404 errors (can this be a Readium problem because of `document.write()` which is used specifically for these web browsers that do not support `BlobURI`?)

**Comment by rkwright** [comment]
Just tried the book on Windows 7 in Parallels and Windows 10 in Parallels - both worked without problems.  Then tried Windows 10 on my wife's Lenovo laptop and ,,,  nothing interactive worked,  Got to the Compass Page and couldn't get out.  Readium's page next would move me to the different Compass Pages (i.e. different Enter buttons).  But couldn't "enter" the chapter nor did the navigation icons (Home, Compass, Pyramid, Next Steps).  Truly weird.

**Comment by danielweck** [comment]
Can you confirm that in both Windows 10 environments the Chrome version was 49?

**Comment by rkwright** [comment]
Yes, both were Chrome 49.0.2623

**Comment by danielweck** [comment]
Related (FXL scaling issue): https://github.com/readium/readium-js-viewer/issues/504#issuecomment-197451880

**Comment by danielweck** [comment]
Ah, I found the source of the problem! (both FXL scaling error, and broken internal navigation)
This is not a bug in Readium. The HTML scaling function is fine.

Culprit in `idGeneratedScript.js`:
```javascript
function goToDestination(ref) {
window.location.href = ref;
}
```

Explanation: any dynamic / scripted redirect  (via `window.location.href` or any other means) of the iframe that hosts EPUB content documents, will *always* break Readium (in several critical ways). That's because Readium can only preprocess and handle hyperlinks that are statically encoded (represented in a declarative way in the HTML files). Using scripted navigation is bad practice in the general case anyway, although I must admit that maybe it works fine in iBooks (and other reading systems) that capture / intercept dynamic URI loading.

In Readium, it may have "looked" like everything is working fine with some combination of web browsers / OS, but in fact the HTML is forcibly loaded into the iframe with no reading system intervention / checks / injections (MathJax, navigator.epubReadingSystem, annotations CSS, viewport dimensions, audio Media Overlays, etc.). In other words: this leads to a complete disconnection of the displayed HTML and the hosting reading system. It's just like loading the HTML file directly inside any arbitrary `iframe`.

I am filing a new issue: https://github.com/readium/readium-shared-js/issues/275
