### ISSUE TITLE
How to make epub book opens in full screen mode

### ISSUE THREAD

**Issue by mahag** [readium/readium-js-viewer#550]
What are the changes that I should apply into  readium-js-viewer_all_LITE.js in order to make book appear in full screen mode once the index.html loads?
As if i need to trigger buttFullScreenToggle once page loads. 
I tried to add the js document.getElementById('buttFullScreenToggle').click(); but didnt work

**Comment by pervy-sage** [comment]
Im having the same issue but mine is with iframe and allowfullscreen. I embedded my reader into my site and i thought allowing full screen will make the full screen button appear but it doesnt. I know its not my code because I tested this with youtube and some other iframes and it worked fine. I also tried this on several different browsers. Safari, IE and chrome

**Comment by danielweck** [comment]
mahag, the full screen API has a security policy that requires user interaction in order to prevent malicious use of content that occupies the entire screen. So programmatic toggling is not recommended.

https://github.com/readium/readium-js-viewer/issues/562
