### ISSUE TITLE
【Question】How to load local epub file using cloud-reader-lite?

### ISSUE THREAD

**Issue by hz0324** [readium/readium-js-viewer#579]
Hi, I am trying to build a web app that can open epub book directly from user's local file system.
I have successfully made the cloud-reader-lite load and open an epub book from a remote cloud server. The url I am using is as below (I am running the cloud-reader-lite on my machine):

http://127.0.0.1:8080/readium-js-viewer/dist/cloud-reader-lite/index.html?epub=http://allthebooks.oss-cn-hangzhou.aliyuncs.com/x145542038256541.epub

I believe there is a way to open a file on user's machine. 
I think at least there are two possible approachs.

First, replace the "epub=xxxx" in the URL above with a local url, such as "index.html?epub=[local//book.epub]", but I don't know how to do this exactly. If you know how, please let me know.

Second, I think readium must read the book url as a parameter input and pass it to a certain function. That function parse the url and display the book. It is possible to tune this very method to make it work with a local epub file (eg, using the FileReader API). But now I don't know how to find this special method. Can you guys please tell me where to find it? Thanks

**Comment by danielweck** [comment]
You can already "import" a local EPUB file into the Readium cloud reader, but not via the `file://` URL scheme / protocol (which web browsers do not support fully due to security considerations, for example `XmlHttpRequest` is disabled).

Instead, you have to drag-and-drop a file from your file explorer into the browser window where the Readium app is loaded. This creates an in-memory binary buffer (URI "blob") containing the entire EPUB, so bear in mind that there are limitations compared with loading a proper HTTP URL (performance, audio/video streaming, etc.).

**Comment by hz0324** [comment]
Thank you very much. I figured it out by looking at the code, so I said "please ignore it".
I really appreciate your reply and kindness.
