### ISSUE TITLE
[QUESTION] How to render a single book page without the reader UX?

### ISSUE THREAD

**Issue by UncleGene** [readium/readium-js-viewer#701]
Is there any example/simple way to create a minimalistic reader that shows a single book page (in a predefined container) and have only prev/next navigation?

**Comment by UncleGene** [comment]
The usage I was looking for was to have a reading pane on half of a screen,
and additional interactions/navigation on another half.
It does not seem that Readium is designed the way to allow more granular
usage, but I hoped I just was missings something...

**Comment by danielweck** [comment]
As @rkwright alluded to, the *lite* variant of the cloud / web reader is purely a "reader" app (no "library" view).

That would be a good starting point. Then, you could strip-down the existing UI by altering the HTML templates and CSS files that define the application UI (for example, to hide all but the previous/next arrows). Alternatively, you could also modify the HTML / CSS in order to display the interaction/navigation features as per your above description.

At any rate ; to answer your original question ; there isn't any "example/simple way to create a minimalistic reader", as I am afraid this it not an out-of-the-box / off-the-shelf feature that Readium cloud/web reader is currently geared for (in other words, you would have to implement this yourself).
