### ISSUE TITLE
Stop the content loading in Blob

### ISSUE THREAD

**Issue by sreejithmangattil** [readium/readium-js-viewer#737]
*General Instructions*

In readium js viewer, all contents are loading in iframe as **Blob**. I want to load the exact HTML/XHTML/HTM into the iframe instead of loading the blob.

#### Expected Behaviour
Readium should load actual content in the iframe instead of loading Blob

#### Observed behaviour
*Instead, Readium does loading Blob file in an iframe

**Comment by danielweck** [comment]
The `readium-js` / `readium-shared-js` iframes only load BlobURIs under the following conditions:

* a zipped / packaged EPUB is loaded, instead of an unzipped / exploded publication.
* an unzipped / exploded EPUB is loaded, but the publication contains obfuscated fonts.

In other words, the iframe will load a regular URL with any unzipped / exploded publications that do not have obfuscated fonts.

There was an experiment with ServiceWorkers to create an abstraction layer on top of a zipped / packaged EPUB, in order to emulate "real" URLs such as `https://domain.com/book.epub/path/to/publication/resource.html` (where `book.epub` is a zip container). This was just an experiment with several major caveats, so it was never pushed into the main code trunk:
https://github.com/readium/readium-js-viewer/tree/feature/ServiceWorker
https://github.com/readium/readium-js/tree/feature/ServiceWorker
https://github.com/readium/readium-shared-js/tree/feature/ServiceWorker
